### ISSUE TITLE
A potential bug with Tab::$outstandingDrinks, and maybe other collections too

### ISSUE THREAD

**Issue by davidwilliams7436** [yourwebmaker/cqrs.nu-php#85]
I'm new to ES and I'm trying to learn more about it using your project (btw, thanks 👍 ).

While debugging the code trying to figure out how the `AggregateRootBehaviour::reconstituteFromEvents()` (from `EventSauce`) actually works, I've notice a strange behaviour of the `Cafe\Domain\Tab\Tab` object: it seems to keep only the last "outstanding drink", ignoring all previously added. The same probably applies to the `$outstandingFood` collection as well.

Steps to reproduce:

1. Open a tab
2. Order one drink, submit with the Place Order button
3. Order another drink, submit (this is important, must be done as a new event)

At this point you should have 3 records in the `aggregate_tab` db table: one `cafe.domain.tab.events.tab_opened` and two `cafe.domain.tab.events.drinks_ordered`.

And here I did my silly debugging by `var_dump`ing the `$tab` variable right after [this line](https://github.com/yourwebmaker/cqrs.nu-php/blob/faba6077ffd6673a12ba239117b4fda81c9951c9/src/Application/Write/TabHandler.php#L55). Turned out the `$outstandingDrinks` property has only one item (a drink from the second event). I would expect to see both drinks here, unless I'm completely missing the point how this should work.
The reason why it happens is that we have two events of the `cafe.domain.tab.events.drinks_ordered` type and they both are applied by the `reconstituteFromEvents()` method. However, the `Tab::applyDrinksOrdered()` method, before doing anything else, sets the `$outstandingDrinks` property to an empty collection ([here](https://github.com/yourwebmaker/cqrs.nu-php/blob/faba6077ffd6673a12ba239117b4fda81c9951c9/src/Domain/Tab/Tab.php#L150)), clearing any existing items.
After commenting this line both drinks appear in the `$outstandingDrinks` collection.

Now I'm a bit confused because this line was added quite long ago ([over a year ago](https://github.com/yourwebmaker/cqrs.nu-php/commit/4cc117037c01b2723255bf6da9733fd68cecab87?diff=split#diff-1057983c757529de7f31e6566f80294eed6aad785aea5626aeb98480cb4a2837R130), if I see not mistaken). Is it possible that this hasn't been noticed before?

As I wrote at the beginning, I'm just trying to get a grasp on how ES works so it's quite possible that I'm just talking stupid things here.
Can someone verify this, please?

**Comment by yourwebmaker** [comment]
Hey @davidwilliams7436 

I'm stuck an issue while installing the project locally due to my composer version (2.3.*). I think I will need to upgrade the SF version and it will work. After that I will investigate your issue, but I think it's a bug.

Get back to you tomorrow or so ;) 

Thanks for the interest in my project ;) Hope you're learning something with it. That was the main reason the project was developed :) .

And sorry for my late reply. I simply deactivate all notifications hahahaha

**Comment by yourwebmaker** [comment]
Hi @davidwilliams7436 . It took a while, but it's fixed now. Thanks for your report!
